### ISSUE TITLE
多轮对话

### ISSUE THREAD

**Issue by RyanOvO** [Nobody-ML/SoulStar#3]
查看了下data.json，数据不错，点赞；请问有多轮对话的数据嘛？多轮对话的效果怎样？

**Comment by Nobody-ML** [comment]
多轮对话的例子见https://github.com/Nobody-ML/HeartLink，数据整理中，效果挺不错的～

**Comment by Nobody-ML** [comment]
多轮对话的例子见[https://github.com/Nobody-ML/HeartLink]，数据整理中，效果挺不错的～

**Comment by Nobody-ML** [comment]
多轮对话的例子见 https://github.com/Nobody-ML/HeartLink 数据整理中，效果挺不错的～
